

services:
  nginx:
    image: local-nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-network

  python-app:
    image: local-python-app   
    build:
      context: ./Python 
    container_name: python_app
    ports:
      - "8000:8000"
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge
